access_tokens:
    type:        rest
    resource:    Da\OAuthServerBundle\Controller\AccesstokenController
    prefix:      api

users:
    type:        rest
    resource:    Da\OAuthServerBundle\Controller\UserController
    prefix:      api

userlinks:
    type:        rest
    resource:    Da\OAuthServerBundle\Controller\UserLinkController
    prefix:      api

clients:
    type:        rest
    resource:    Da\OAuthServerBundle\Controller\ClientController
    prefix:      api

authorizations:
    resource:    Da\OAuthServerBundle\Controller\AuthorizeController

infos:
    resource:    Da\OAuthServerBundle\Controller\InfoController
    prefix:      api

security:
    resource:    Da\OAuthServerBundle\Controller\SecurityController

registration:
    resource:    Da\OAuthServerBundle\Controller\RegistrationController

profile:
    resource:    Da\OAuthServerBundle\Controller\ProfileController