parameters:
    da_oauth_server.user_provider.authspace_email.class: Da\OAuthServerBundle\Security\AuthSpaceEmailUserProvider
    da_oauth_server.authspace_manager.class: Da\OAuthServerBundle\Doctrine\AuthSpaceManager

services:
    da_oauth_server.user_provider.authspace_email:
        class: %da_oauth_server.user_provider.authspace_email.class%
        public: false
        arguments: [@fos_user.user_manager, @service_container, @da_oauth_server.authspace_manager]

    da_oauth_server.authspace_manager.default:
        class: %da_oauth_server.authspace_manager.class%
        public: false
        arguments: [@fos_oauth_server.entity_manager, %da_oauth_server.authspace.class%]
