language: php

php:
  - 5.3
  - 5.4

env:
  - SYMFONY_VERSION="2.1.*"
  - SYMFONY_VERSION="2.2.*"
  - SYMFONY_VERSION="2.3.*"

before_script: 
  - composer require symfony/dependency-injection:${SYMFONY_VERSION} --dev

script: phpunit --coverage-text